### ISSUE TITLE
Request for the author to re-share the source code

### ISSUE THREAD

**Issue by yedvvard** [ChenHongruixuan/SRGCAE#1]
@ChenHongruixuan :

Hello,

I came across your recent paper where you mentioned that the source code was open-sourced. However, I was unable to find the actual source code in this GitHub repository. Have I missed something? Can you please re-share the source code with us?

Thank you for your time and consideration. I appreciate your work and look forward to hearing from you soon.

Best regards,
yedvvard

**Comment by ChenHongruixuan** [comment]
Hi yedvvard,

Thank you for your interest in our work, and sorry for our late upload. We have uploaded our code and provided one example based on a multimodal dataset, the Shuguang dataset. Hope our code can give some help to your research.

Best wishes,

**Comment by yedvvard** [comment]
Hi ChenHongruixuan,

Thank you for your response and for uploading the source code! I really appreciate your help and your quick action in addressing my request. Wish you success in your scientific research career.

Best regards,
