### ISSUE TITLE
about algorithm for image segmentation

### ISSUE THREAD

**Issue by luolahou** [ChenHongruixuan/SRGCAE#3]
Hello, I am unable to use your code to achieve the required results. I think this is because the code uses the SLIC algorithm for image segmentation, but the article mentions using the FNEA algorithm. Do you have the code for the FNEA algorithm? thank you very much. Wishing you all the best in your future research

**Comment by ChenHongruixuan** [comment]
Hi, thank you for your interest in our work! 

According to our test, the SLIC algorithm gives results in the local structure consistency part that are close to those in the original paper and in the non-local structure consistency part that are better than those in the original paper. However, after fusion, the results obtained are slightly inferior to those in the original paper. 

The FNEA algorithm we use is from the software eCognition, which is commercial software, and therefore we cannot provide it to you. We suggest that you could see if there is any library that implemented the FNEA algorithm or adjust the bandwidth to see if you can get a better result.

Best regards,

**Comment by luolahou** [comment]
![SRGCAE_EdgeConc_1685110728 4216504_DI](https://github.com/ChenHongruixuan/SRGCAE/assets/133310640/e3d3f359-8a0a-41f4-a6ac-5b2d5c3bfe30)
![SRGCAE_EdgeConc_DI](https://github.com/ChenHongruixuan/SRGCAE/assets/133310640/d66a4138-ea90-495d-b506-57497a8da509)
Thank you for your answer! But I can only get the results of the first image using the code you provided. The second image is your reference image, and I don't know what's wrong with it. If you could give me some suggestions, it would be very helpful. Thank you very much

**Comment by ChenHongruixuan** [comment]
Thank you for your question! The pre-trained model we uploaded was trained on the Shuguang dataset using our current hyperparameters. Bandwidth parameters are important, and perhaps you could tune these parameters considering the difference in programming environments.

**Comment by luolahou** [comment]
Thank you for your patient answer！I wish you success in your work！
